--- Extra read-only role
CREATE ROLE readerole WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  PASSWORD 'Ec0t1x1Rd4';

GRANT SELECT ON ALL TABLES IN SCHEMA public TO readerole;

