[mypy]
;plugins = sqlalchemy.ext.mypy.plugin, API_models/mypy/plugin.py
;plugins = API_models/mypy/plugin.py
files = API_models,API_operations,BG_operations,DB,BO,data,FS,ML,helpers,ML,gpu_jobs_runner.py
;files = ML
# Notes: DB is excluded as it uses the sqlalchemy plugin which need a recent mypy and pip says:
# The conflict is caused by:
#    pydantic 1.9.2 depends on typing-extensions>=3.7.4.3
#    tensorflow 2.6.0 depends on typing-extensions~=3.7.4
#    mypy 0.942 depends on typing-extensions>=3.10

#strict = True
#implicit_reexport = True
# There are files in upgrade directory which confuse mypy 1.2.0 unless below is set
#no_namespace_packages = True
namespace_packages = True
explicit_package_bases = True
ignore_missing_imports = True

# Tip: cleanup all in a shell: (venv38) $ python3.8 -m pip freeze | xargs python3.8 -m pip uninstall -y

# Common typing issues:
# case1: no .rowcount in executed queries (SQLAlchemy typings issue).
# case2: DB model fields do not get typed correctly as columns. It's the underlying Python type instead (SQLAlchemy typings issue).
# case4: SQLAlchemy Row (from Result iter) is not typed an a Mapping (when it _is_, keys being query columns) (SQLAlchemy typings issue)
# case5: no .description in cursors (SQLAlchemy typings issue).
# case6: no typing stub or typing in lib
[mypy-numpy.*]
ignore_missing_imports = True
[mypy-tensorflow.*]
ignore_missing_imports = True
[mypy-tensorflow_addons.*]
ignore_missing_imports = True
[mypy-tensorflow_hub.*]
ignore_missing_imports = True
[mypy-cv2.*]
ignore_missing_imports = True
[mypy-imgaug.*]
ignore_missing_imports = True
[mypy-sklearn.*]
ignore_missing_imports = True
[mypy-db_upg.*]
ignore_missing_imports = True
[mypy-pgvector.*]
ignore_missing_imports = True